[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bert-nlp-project"
version = "0.1.0"
description = "End-to-end BERT text classification project"
requires-python = ">=3.9"
dependencies = []
