# Dataset options
# If using HF dataset (e.g., ag_news), set name and set train/validation to null
# If using local CSVs, set name: null and provide train_file/validation_file

seed: 42
output_dir: models

model:
  pretrained_name: bert-base-uncased
  num_labels: 4  # adjust for your dataset

trainer:
  num_train_epochs: 3
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 32
  gradient_accumulation_steps: 1
  learning_rate: 2.0e-5
  weight_decay: 0.01
  warmup_ratio: 0.06
  fp16: true
  logging_steps: 50
  eval_strategy: epoch
  save_strategy: epoch
  load_best_model_at_end: true
  metric_for_best_model: eval_f1
  greater_is_better: true
  early_stopping_patience: 2

# Use one of the following dataset settings

# Option A: HF datasets
dataset:
  name: ag_news
  text_column: text
  label_column: label
  train_split: train
  validation_split: test
  train_file: null
  validation_file: null

# Option B: Local CSVs
# dataset:
#   name: null
#   text_column: text
#   label_column: label
#   train_file: data/train.csv
#   validation_file: data/validation.csv
